### ISSUE TITLE
Request File Manager

### ISSUE THREAD

**Issue by knkrth** [globalpolicy/PhoneMonitor#1]
Hi, Nice work. Is there possible to add file manager to the commands? So that local storage can be access on mobile.

**Comment by globalpolicy** [comment]
Thanks. Glad you like it.
A file manager of some sort should be possible, though the implementation-specific details of such a feature would need to be worked out first.
Feel free to fork and open a pull request if you manage to add the said functionality.

**Comment by knkrth** [comment]
Ok Thanks.
