### ISSUE TITLE
Failed to read setting from server at AppSettings.getServerTalkInterval() (Permission denied)

### ISSUE THREAD

**Issue by elmagekmosaad** [globalpolicy/PhoneMonitor#18]
W/phonemonitor: Failed to read setting from server at AppSettings.getServerTalkInterval()
    Connection refused
    Failed to read local setting at AppSettings.getServerTalkInterval()
    /data/user/0/com.monitor.phone.s0ft.phonemonitor/files/phonemonitorsettings.json (Permission denied)

![image](https://user-images.githubusercontent.com/19142989/167449175-14f58e23-535a-4341-8184-0c35b656b059.png)

**Comment by BlackSloth1** [comment]
what commands are you using?

**Comment by elmagekmosaad** [comment]
i fixed error replaced local host to my local ip because i use xampp to test

**Comment by elmagekmosaad** [comment]
> what commands are you using?

where commands to use i can't see anything else phone info as logs 
![image](https://user-images.githubusercontent.com/19142989/167461360-a991ff9f-6e9b-4d0c-a99c-c5039142696f.png)
and from icon setting it show as this image ! :]
![image](https://user-images.githubusercontent.com/19142989/167461491-12ed01a4-4e29-4ad6-8edf-ef9fa76c8e49.png)

**Comment by BlackSloth1** [comment]
using sms or email

**Comment by BlackSloth1** [comment]
read the wiki
