### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lordcharlx** [globalpolicy/PhoneMonitor#5]
its awesome but why not make it more user friendly by adding up a sql file instead of setting approval in phpmyadmin

**Comment by globalpolicy** [comment]
Would it make that big of a difference? I mean, to get a usable apk, one has to know how to use Android Studio and similarly, for setting up the web panel, one has to know the basics of webhosting and some PHP and SQL. So, provided a person has those skills, they probably don't mind changing a field in the database manually. 
It maybe (a little?) more convenient to change an sql file (for changing users' approval status, no less) but it probably won't make that big a difference, at least difference commensurate with the extra code that the convenience would entail.

**Comment by lordcharlx** [comment]
thanks issue fixed  ! nice project
