### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lordcharlx** [globalpolicy/PhoneMonitor#6]
please why am i getting this error 
![2018-01-25-092140_1366x768_scrot](https://user-images.githubusercontent.com/5570136/35380496-51c1d552-01b1-11e8-853f-65b687601fd6.png)

**Comment by globalpolicy** [comment]
I dunno why it is saying that.
Just opened the project and compiled it successfully here.

**Comment by cool125** [comment]
hey, i required some changing in code. can u do it or have u finished this project?

**Comment by globalpolicy** [comment]
Sorry, I'm not working on it any more.
Open to PR's though.

**Comment by cool125** [comment]
kindly contact me on whatsapp  i just need 3 small modification in code that will hardly take ur 5 minutes.. kindly text me here +16573013628

**Comment by globalpolicy** [comment]
Hello,
I don't happen to use whatsapp or any other instant messaging service.
So, if you can describe exactly what you are looking for in the
PhoneMonitor right here, maybe something could come out it.

**Comment by cool125** [comment]
please admin check your Gmail  ( yciloplabolg@gmail.com ) .. i have send u details in email

**Comment by lordcharlx** [comment]
@cool125 why not discuss your issue here let us all benefit and learn !

**Comment by cool125** [comment]
@lordcharlx  dear i dont think so i need to spam commenting to explain my required changes..  if admin will need to apply that changes to code then he will surely mention that changes here in app description.. if u are an expert coder then privately contact me we can discuss on other projects that have almost same features.. my whatsapp id is +16573013628
