### ISSUE TITLE
Not Working: App didn't connect to web panel!

### ISSUE THREAD

**Issue by Metasploiter** [globalpolicy/PhoneMonitor#8]
hello.
thanks globalpolicy for this project
but i have issue i have been build the APK file with android studio and deploying the web panel without any issue but unfortunately the app and web panel didn't connect to each other

**Comment by warifp** [comment]
same

**Comment by warifp** [comment]
how to fix?

**Comment by warifp** [comment]
application android cannot open, has ben installed, cannot opened.

**Comment by warifp** [comment]
**fixed!! : this is application work on api -21 , api 21+ not work.**
